name: teste - Run ETL BACEN

on:
  workflow_dispatch:
  schedule:
    # Run at 8:00 AM on March 6, 2025
    - cron: '0 8 6 3 4'
    # Run at 8:00 AM on April 4, 2025
    - cron: '0 8 4 4 5'
    # Run at 8:00 AM on May 9, 2025
    - cron: '0 8 9 5 5'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R dependencies
        run: |
          R -e "if (!requireNamespace('needed-package', quietly = TRUE)) install.packages('needed-package')"

      - name: Run R script
        run: |
          Rscript bacen/scripts/102_bacen_ETL_v01_download_simples.R.R
