name: Run BACEN Data Script

on:
  workflow_dispatch:
  schedule:
    - cron: '17 12 6 3 *'  # March 6th, 9:17 AM São Paulo (UTC-3)
    - cron: '19 12 7 4 *'  # April 7th, 9:19 AM São Paulo (UTC-3)

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0' # Or your desired R version

#      - name: Install R packages if needed
#        run: |
#          R_PACKAGES="GetBCBData openxlsx tidyverse"
#          INSTALLED_PACKAGES=$(Rscript -e "paste(.packages(all.available = TRUE), collapse = ' ')")
#          MISSING_PACKAGES=$(echo "$R_PACKAGES" | tr ' ' '\n' | grep -vxF -f <(echo "$INSTALLED_PACKAGES" | tr ' ' '\n'))
#          if [[ -n "$MISSING_PACKAGES" ]]; then
#            Rscript -e "install.packages(c($(echo "$MISSING_PACKAGES" | tr '\n' ',')))"
#          fi

      - name: Run R script
        run: sudo Rscript ${{ github.workspace }}/bacen/scripts/102_bacen_ETL_v01_download_simples.R

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update bacen data"
          file_pattern: bacen/lake/*.xlsx bacen/lake/*.rdata
